---
driver           :
  name           : docker_cli

verifier         :
  name           : serverspec
  remote_exec    : false
  default_pattern: true

transport :
  name    : docker_cli

provisioner:
  name     : shell
  sudo     : false

platforms         :
  - name          : colossal
    driver_config :
      image       : quay.io/ahelal/colossal:dev

suites                      :
  - name                    : app
    driver_config           :
      environment           :
          CONSUL            : "pilot-consul"
          APP_NAME          : "pilot-app"
          APP_PORT          : 8080
          APP_EXEC          : resu app:app -- /app.py
          APP_TAGS          : "TEST,v1.1.1,Development"
          APP_RESTARTS      : 1
          APP_TIMEOUT       : 0
          APP_HEALTH_EXEC   : "curl -fsSo /dev/null http://127.0.0.1:8080"
          SERVICE_NAME_23   : "pilot-redis"
          SERVICE_PORT_23   : "6379"
          SERVICE_MODE_23   : "tcp"
          HAPROXY_STATS     : True
          HAPROXY_EXPORTER  : True
          LOG_LEVEL         : "debug"
      link                  :
      - pilot-consul
      publish               :
       - 8080:8080
       - 3212:3212
       - 9101:9101
    provisioner             :
      script                : "test/integration/app/setup.sh"

  - name                    : nginx
    driver_config           :
      environment           :
          CONSUL            : "pilot-consul"
          APP_NAME          : "pilot-nginx"
          APP_PORT          : 80
          APP_EXEC          : "nginx"
          APP_RESTARTS      : 1
          APP_TIMEOUT       : 0
          APP_HEALTH_EXEC   : "curl -fsSo /dev/null http://127.0.0.1/status"
          SERVICE_NAME_1    : "pilot-app"
          SERVICE_PORT_1    : "8080"
          SERVICE_MODE_1    : "http"
      link                  :
      - pilot-consul
      publish               :
       - 80:80
    provisioner             :
      script                : "test/integration/nginx/setup.sh"

  - name                    : redis
    driver_config           :
      environment           :
          CONSUL            : "pilot-consul"
          APP_NAME          : "pilot-redis"
          APP_PORT          : 6379
          APP_RESTARTS      : 1
          APP_TIMEOUT       : 0
          APP_EXEC          : "redis-server /etc/redis.conf"
          APP_HEALTH_EXEC   : "redis-cli ping"
      link                  :
      - pilot-consul
      publish               :
       - 6379:6379
    provisioner             :
      script                : "test/integration/redis/setup.sh"
