version: '3'
services:
  consul:
    image: consul
    ports:
      - "8300:8300"
      - "8301:8301"
      - "8301:8301/udp"
      - "8302:8302"
      - "8302:8302/udp"
      - "8400:8400"
      - "8500:8500"
    environment:
      - CONSUL_BIND_INTERFACE=eth0
  nginx:
    build:
      context: ./nginx
    depends_on:
      - consul
    environment:
      - CONSUL=consul
    links:
    - consul
    ports:
      - "8000:80"
      - "3212:3212"
  app:
    build:
      context: ./app
    depends_on:
#      - redis
      - consul
    environment:
      - CONSUL=consul
    links:
    - consul
    ports:
      - "8080:8080"
  app2:
    build:
      context: ./app
    depends_on:
#      - redis
      - consul
    environment:
      - CONSUL=consul
    links:
    - consul
 #   env_file:
 #     - ./app/consul.env
  # redis:
  #   build:
  #     context: ./redis
  #   ports:
  #     - "6379:6379"
  #   env_file:
  #     - ./redis/consul.env
  #   depends_on:
  #     - consul
  #   links:
  #   - consul