require_relative '../../helper_spec.rb'

describe file('/etc/haproxy/haproxy.cfg') do
  its(:content) { should contain '# Auto generated by Consul template' }
end

describe 'Stats are enabled' do
  describe command 'curl "http://localhost:3212/"' do
    its(:exit_status) { should eq 0 }
    its(:stdout) { should contain 'Statistics Report' }
  end
end
